---
version: '3.9'

services:
  api:
    container_name: node_products_api
    image: node_products_api
    restart: always
    build:
      context: .
      dockerfile: dev.dockerfile
    environment:
      - NODE_ENV=Docker
    volumes:
      - ./src:/app/src
    ports:
      - 8081:8081

  nginx:
    container_name: products_api_proxy
    image: nginx:1.20-alpine
    restart: always
    ports:
      - 80:80
      - 443:433
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

  mongo:
    container_name: products_api_mongo_db
    image: mongo:4.0.26-xenial
    volumes:
      - ./data/mongo:/data/db:delegated
    ports:
      - 27017:27017
    logging:
      driver: none
