---
version: '3.9'

services:
  api:
    container_name: node_products_api_dev
    image: node_products_api_dev
    restart: always
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: dev.dockerfile
    environment:
      - MONGODB_URI=mongodb://mongodb/products_api
      - MONGODB_USER=
      - MONGODB_PASSWORD=
      - NODE_ENV=Docker
    volumes:
      - ./src:/app/src
    ports:
      - 8000:8000
    command: ['start:dev']

  nginx:
    container_name: products_api_proxy
    image: nginx:1.20-alpine
    restart: always
    ports:
      - 80:80
      - 443:433
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

  mongodb:
    container_name: products_api_mongo_db
    image: mongo:4.0.26-xenial
    volumes:
      - ./data/mongo:/data/db:delegated
    ports:
      - 27017:27017
    logging:
      driver: none
